baseURL = "http://localhost/"
title = "ProfiCAD"
defaultContentLanguage = "cs"
defaultContentLanguageInSubdir = true

[languages]
  [languages.cs]
    languageName = "Čeština"
    weight = 1
  [languages.de]
    languageName = "Deutsch"
    weight = 2
  [languages.en]
    languageName = "English"
    weight = 3
  [languages.es]
    languageName = "Español"
    weight = 4

[params]
  appName = "ProfiCAD"
  appVersion = "13.0"
